import type { ProjectProfile } from '../inspector/types.js';
import type { MigrationDecision } from '../strategy/types.js';

export function generateProjectContext(
  profile: ProjectProfile,
  decisions: MigrationDecision[],
): string {
  const date = new Date().toISOString().slice(0, 10);
  const lines: string[] = [
    '# Project context',
    '',
    `Generated by multi-cli-install v2 on ${date}. Regenerate via`,
    '`npx @rwn34/multi-cli-install --refresh-context`.',
    '',
    '## Stack',
    `- Language: ${profile.stack.language}`,
    `- Package manager: ${profile.stack.packageManager}`,
    `- Framework: ${profile.framework.name}${profile.framework.version ? ' ' + profile.framework.version : ''}`,
    '',
    '## Layout (post-install)',
  ];

  // Build post-install dir map: apply reorganize decisions
  const moved = new Map<string, string>();
  for (const d of decisions) {
    if (d.action === 'reorganize' && d.targetPath) {
      moved.set(d.sourcePath, d.targetPath);
    }
  }

  for (const s of profile.dirs.source) {
    const target = moved.get(s.path) ?? s.path;
    const note = moved.has(s.path) ? ` (moved from \`${s.path}/\`)` : '';
    lines.push(`- Source: \`${target}\`${note}`);
  }
  for (const t of profile.dirs.test) {
    const target = moved.get(t.path) ?? t.path;
    const note = moved.has(t.path) ? ` (moved from \`${t.path}/\`)` : '';
    lines.push(`- Tests: \`${target}\`${note}`);
  }
  for (const d of profile.dirs.docs) {
    const target = moved.get(d.path) ?? d.path;
    const note = moved.has(d.path) ? ` (moved from \`${d.path}/\`)` : '';
    lines.push(`- Docs: \`${target}\`${note}`);
  }
  for (const c of profile.dirs.ci) {
    lines.push(`- CI: \`${c.path}\``);
  }

  // Framework-pinned dirs
  const adapted = decisions.filter(d => d.action === 'adapt');
  lines.push('');
  lines.push('## Framework-pinned dirs (NOT moved during install)');
  if (adapted.length > 0) {
    for (const d of adapted) lines.push(`- \`${d.sourcePath}/\``);
  } else {
    lines.push('(none)');
  }

  // Commands
  lines.push('');
  lines.push('## Commands');
  lines.push(`- Test: ${profile.commands.test ? `\`${profile.commands.test}\`` : '(not detected)'}`);
  lines.push(`- Build: ${profile.commands.build ? `\`${profile.commands.build}\`` : '(not detected)'}`);
  lines.push(`- Lint: ${profile.commands.lint ? `\`${profile.commands.lint}\`` : '(not detected)'}`);

  // Conventions
  lines.push('');
  lines.push('## Conventions');
  lines.push(`- Naming: ${profile.conventions.namingStyle}`);
  const lintList = profile.conventions.lintConfig.length > 0
    ? profile.conventions.lintConfig.join(', ')
    : '(none)';
  lines.push(`- Lint config: ${lintList}`);

  // Notes
  lines.push('');
  lines.push('## Notes for AI agents');
  lines.push('When making changes, follow this project\'s existing patterns. Layout above');
  lines.push('reflects the post-install state. Framework-pinned dirs (if any) must not be');
  lines.push('relocated.');
  lines.push('');

  return lines.join('\n');
}
